version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - db

  db:
    image: mysql:8.0  # Ou postgres:latest si tu veux PostgreSQL
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: banque_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: transfert-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banque_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9090:9090"
    depends_on:
      - db
      - keycloak

volumes:
  mysql_data:
